# Change these first
owner: hwittenborn # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Homepage
    url: https://hunterwittenborn.coms
  - name: Matrix
    url: https://matrix.hunterwittenborn.com
  - name: Shlink
    url: https://shlink.hunterwittenborn.com
  - name: makedeb Homepage
    url: https://www.makedeb.org
  - name: makedeb Docs
    url: https://docs.makedeb.org
  - name: makedeb Package Repository
    url: https://mpr.makedeb.org
  - name: makedeb Package Repository (SSH)
    check: "tcp-ping"
    url: mpr.makedeb.org
    port: 22
  - name: makedeb ProGet Instance
    url: https://proget.makedeb.org
  - name: RhinoDrop
    url: https://drop.rhinolinux.org

workflowSchedule:
  responseTime: "*/5 * * * *"
  updates: "0 * * * *"
  uptime: "*/5 * * * *"
